import setData from '../data/content/item-sets.json';
import type { BuildEquipmentState } from '../types';
import { equippedSlot3 } from '../types';

/**
 * Equipment sets: extra bonuses for wearing several pieces of a group together.
 *
 * Generated by `scripts/build-set-data.mjs`. Sets span every slot (a single set
 * can pull in a weapon, the torso, hands, legs and both accessories), so this
 * counts across the whole loadout rather than any one slot's data.
 *
 * The bonuses themselves stay prose. They are things like "Flee success rate is
 * (normal success rate+50)%" and "Grants access to the Double Dao skill", almost
 * none of which map to a channel the calculator has; inventing numbers for them
 * would be worse than showing the player what the game will do.
 */

export interface SetThreshold {
  /** Pieces required. */
  count: number;
  description: string;
}

export interface ItemSet {
  members: string[];
  thresholds: SetThreshold[];
  /** Bonus prose for a set that scales per piece instead of at thresholds. */
  note?: string;
}

export const ITEM_SETS = setData as Record<string, ItemSet>;

/** Set names an item belongs to, keyed by item name. */
const SET_OF_ITEM = new Map<string, string[]>();
for (const [name, set] of Object.entries(ITEM_SETS)) {
  for (const member of set.members) {
    SET_OF_ITEM.set(member, [...(SET_OF_ITEM.get(member) ?? []), name]);
  }
}

export function setsForItem(itemName: string | null | undefined): string[] {
  if (!itemName) return [];
  return SET_OF_ITEM.get(itemName) ?? [];
}

export interface ActiveSet {
  name: string;
  /** How many of the set's pieces this build is wearing. */
  equipped: number;
  total: number;
  /** Thresholds this build has reached. */
  active: SetThreshold[];
  /** Thresholds it has not, so the UI can show what one more piece would buy. */
  upcoming: SetThreshold[];
  note?: string;
}

/**
 * Every item name the build has equipped, across all six slots.
 *
 * Slot 3 is resolved rather than read twice: a build using an off-hand weapon
 * may still carry a stale hands entry, and counting it would complete a set the
 * player is not actually wearing.
 */
export function equippedItemNames(equipment: BuildEquipmentState | undefined): string[] {
  if (!equipment) return [];
  const usingOffHand = equippedSlot3(equipment) === 'offHandWeapon';
  return [
    equipment.primaryWeapon?.selectedWeaponName,
    equipment.armorName,
    usingOffHand ? equipment.offHandWeapon?.selectedWeaponName : equipment.hands?.itemName,
    equipment.legs?.itemName,
    equipment.accessory1?.itemName,
    equipment.accessory2?.itemName,
  ].filter((name): name is string => Boolean(name));
}

/**
 * Which sets a build has pieces of, and which of their thresholds are met.
 *
 * A set the build owns only one piece of is still reported, with `active`
 * empty; that is the case where showing the next threshold is most useful.
 */
/**
 * How many pieces of `setName` the build is wearing.
 *
 * The Dragon King and Dragon Queen sets are the two whose bonus the calculator
 * can actually apply ("+5% total Strength and +3 to its soft cap for each
 * Dragon King item equipped" is arithmetic, not prose), so the piece count is
 * read from the equipment rather than typed in by hand.
 */
export function setPiecesEquipped(
  equipment: BuildEquipmentState | undefined,
  setName: string,
): number {
  const members = new Set(ITEM_SETS[setName]?.members ?? []);
  if (!members.size) return 0;
  return equippedItemNames(equipment).filter(name => members.has(name)).length;
}

export function activeSets(equipment: BuildEquipmentState | undefined): ActiveSet[] {
  const equipped = equippedItemNames(equipment);
  if (!equipped.length) return [];

  const counts = new Map<string, number>();
  for (const item of equipped) {
    for (const name of setsForItem(item)) counts.set(name, (counts.get(name) ?? 0) + 1);
  }

  return [...counts.entries()]
    .map(([name, count]) => {
      const set = ITEM_SETS[name];
      return {
        name,
        equipped: count,
        total: set.members.length,
        active: set.thresholds.filter(threshold => count >= threshold.count),
        upcoming: set.thresholds.filter(threshold => count < threshold.count),
        ...(set.note ? { note: set.note } : {}),
      };
    })
    .sort((a, b) => b.active.length - a.active.length || a.name.localeCompare(b.name));
}
