/**
 * Per-item effects for weapons and armour.
 *
 * Items carry effects beyond their headline numbers, and many scale with **UL**:
 * the upgrade points spent on that piece. "Increases Light ATK by UL/2" is worth
 * nothing on a fresh weapon and grows as it is upgraded, so the magnitude is
 * stored as `base + UL * ulMultiplier` and resolved here against the build's own
 * upgrade spend.
 *
 * Generated by `scripts/build-item-effects.mjs`.
 */
import type { ArmorUpgradePoints, ElementKey, ResistKey, StatKey, WeaponUpgradePoints } from '../types';
import content from '../data/content/item-effects.json';

export interface ItemEffectValue {
  kind: 'stat' | 'derived' | 'elementalAttack' | 'resistance';
  key: string;
  base: number;
  /** Multiplied by the piece's UL. Zero for a flat bonus. */
  ulMultiplier: number;
  /**
   * The top of a rolled range, when the wiki writes one ("+2-4 CEL").
   *
   * These are per-item RNG: a copy of the item rolls a value in the range when
   * it drops and keeps it, so the build has to say which roll it owns. `base` is
   * the bottom of the range and the default.
   */
  rollMax?: number;
}

export interface ItemEffect {
  name: string;
  description: string;
  /**
   * `always` applies on its own. `conditional` is quantified but gated on
   * something the calculator cannot see, so it is opt-in. `reference` carries no
   * numbers at all and never changes a build.
   */
  applies: 'always' | 'conditional' | 'reference';
  effects: ItemEffectValue[];
}

const WEAPON_EFFECTS = content.weapons as Record<string, ItemEffect[]>;
const ARMOR_EFFECTS = content.armors as Record<string, ItemEffect[]>;
/** Hands, shields, legs and accessories, equipment slots 3 to 6. */
const GEAR_EFFECTS = content.gear as Record<string, ItemEffect[]>;

export function weaponEffects(name: string | null | undefined): ItemEffect[] {
  return (name && WEAPON_EFFECTS[name]) || [];
}

export function armorEffects(name: string | null | undefined): ItemEffect[] {
  return (name && ARMOR_EFFECTS[name]) || [];
}

/**
 * Effects for a hands, shield, legs or accessory item.
 *
 * These slots have no stat columns on the wiki, so unlike a weapon or a piece of
 * armour an item here contributes *nothing* except through these effects.
 */
export function gearEffects(name: string | null | undefined): ItemEffect[] {
  return (name && GEAR_EFFECTS[name]) || [];
}

/**
 * UL for a piece: every upgrade point spent on it, across all channels.
 *
 * The calculator splits upgrades per channel while the wiki talks about one
 * number, so the channels are summed. A legacy `upgradeLevel` of 5 fills three
 * channels and therefore reads as UL 15.
 */
export function weaponUL(points: WeaponUpgradePoints | undefined): number {
  if (!points) return 0;
  return points.power + points.critical + points.accuracy + points.durability;
}

export function armorUL(points: ArmorUpgradePoints | undefined): number {
  if (!points) return 0;
  // Three channels: a torso has no durability track.
  return points.armor + points.magicArmor + points.evade;
}

/** The magnitude of one effect at a given UL, floored as the game does. */
export function valueAtUL(value: ItemEffectValue, ul: number, roll?: number): number {
  const rolled = value.rollMax === undefined ? value.base : clampRoll(value, roll);
  return Math.floor(rolled + ul * value.ulMultiplier);
}

/**
 * The roll a build has for a ranged effect, held inside the range.
 *
 * Defaults to the bottom of the range: an unconfigured build then understates
 * rather than claiming an item rolled well.
 */
export function clampRoll(value: ItemEffectValue, roll: number | undefined): number {
  if (value.rollMax === undefined) return value.base;
  if (roll === undefined || !Number.isFinite(roll)) return value.base;
  return Math.min(Math.max(Math.floor(roll), value.base), value.rollMax);
}

/**
 * Key identifying one rolled value, for the per-build roll overrides.
 *
 * Down to the value rather than the effect, because one effect line can state
 * two independent rolls: Bands of the Crocodile is "+1-3 WIL, +1-2 DEF".
 */
export function itemRollKey(itemName: string, effectIndex: number, valueIndex: number): string {
  return `${itemName}:${effectIndex}:${valueIndex}`;
}

export interface ItemBonuses {
  stats: Partial<Record<StatKey, number>>;
  derived: Record<string, number>;
  elementalAttack: Partial<Record<ElementKey, number>>;
  /**
   * Percentage elemental resistance an item grants in its own text.
   *
   * Armour states these in a curated map instead, which the evaluator already
   * applies, so an armour's text is deliberately not read for them; see
   * `scripts/build-item-effects.mjs`. What lands here comes from weapons and
   * from slots 3-6, neither of which has a structured field for it.
   */
  resistances: Partial<Record<ResistKey, number>>;
}

const EMPTY: ItemBonuses = { stats: {}, derived: {}, elementalAttack: {}, resistances: {} };
/** Shared so the common case of no chosen rolls allocates nothing per call. */
const NO_ROLLS: Record<string, number> = Object.freeze({});

/** Key identifying one conditional effect, for the opt-in toggles. */
export function itemConditionalKey(itemName: string, index: number): string {
  return `${itemName}:${index}`;
}

/**
 * Sums the effects of one item at its upgrade level.
 *
 * `always` effects count on their own; `conditional` ones only when the user has
 * switched them on. `reference` effects carry no numbers and are skipped.
 */
export function bonusesForItem(
  itemName: string | null | undefined,
  effects: ItemEffect[],
  ul: number,
  conditionals: Record<string, boolean>,
  into: ItemBonuses,
  rolls: Record<string, number> = NO_ROLLS,
): ItemBonuses {
  if (!itemName) return into;
  effects.forEach((effect, index) => {
    if (effect.applies === 'reference') return;
    if (effect.applies === 'conditional' && !conditionals[itemConditionalKey(itemName, index)]) return;
    effect.effects.forEach((value, valueIndex) => {
      const amount = valueAtUL(value, ul, rolls[itemRollKey(itemName, index, valueIndex)]);
      if (!amount) return;
      if (value.kind === 'stat') {
        const key = value.key as StatKey;
        into.stats[key] = (into.stats[key] ?? 0) + amount;
      } else if (value.kind === 'elementalAttack') {
        const key = value.key as ElementKey;
        into.elementalAttack[key] = (into.elementalAttack[key] ?? 0) + amount;
      } else if (value.kind === 'resistance') {
        const key = value.key as ResistKey;
        into.resistances[key] = (into.resistances[key] ?? 0) + amount;
      } else {
        into.derived[value.key] = (into.derived[value.key] ?? 0) + amount;
      }
    });
  });
  return into;
}

/**
 * One equipped slot-3-to-6 item and the upgrade points spent on it.
 *
 * The points are the slot's own two tracks, whatever they are named, since UL is
 * their sum either way.
 */
export interface GearSlotInput {
  itemName?: string | null;
  /**
   * The slot's own two tracks. Typed structurally rather than as a
   * `Record<string, number>` so the per-slot interfaces (which have no index
   * signature) can be passed straight through.
   */
  upgradePoints?: object;
}

/** UL for a hands, legs or accessory piece: both of its tracks summed. */
export function gearUL(points: object | undefined): number {
  if (!points) return 0;
  return Object.values(points).reduce<number>((total, value) => total + (Number(value) || 0), 0);
}

/** Combined weapon, armour and slot 3-6 item bonuses for a build. */
export function itemBonuses(input: {
  weaponName?: string | null;
  armorName?: string | null;
  weaponPoints?: WeaponUpgradePoints;
  armorPoints?: ArmorUpgradePoints;
  /** Hands or off-hand slot, legs, and the two accessory slots. */
  gear?: Array<GearSlotInput | undefined>;
  conditionals?: Record<string, boolean>;
  /** Chosen roll per ranged value, keyed by `itemRollKey`. */
  rolls?: Record<string, number>;
}): ItemBonuses {
  const weapons = weaponEffects(input.weaponName);
  const armors = armorEffects(input.armorName);
  /*
   * Deliberately allocation-free until something is actually equipped.
   *
   * `evaluateBuild` runs on the order of a hundred thousand times per optimizer
   * search and almost none of those builds carry gear, so the empty case walks
   * the slots with a plain loop rather than building intermediate arrays.
   */
  const gear = input.gear;
  let hasGear = false;
  if (gear) {
    for (const slot of gear) {
      if (slot?.itemName && gearEffects(slot.itemName).length) { hasGear = true; break; }
    }
  }
  // Skip the allocation entirely for a build with none.
  if (!weapons.length && !armors.length && !hasGear) return EMPTY;

  const conditionals = input.conditionals ?? {};
  const rolls = input.rolls ?? NO_ROLLS;
  const result: ItemBonuses = { stats: {}, derived: {}, elementalAttack: {}, resistances: {} };
  bonusesForItem(input.weaponName, weapons, weaponUL(input.weaponPoints), conditionals, result, rolls);
  bonusesForItem(input.armorName, armors, armorUL(input.armorPoints), conditionals, result, rolls);
  /*
   * Each slot resolves at its own UL. Two accessory slots can hold different
   * items upgraded to different levels, so a shared UL would misprice both.
   */
  if (gear) {
    for (const slot of gear) {
      if (!slot?.itemName) continue;
      const effects = gearEffects(slot.itemName);
      if (!effects.length) continue;
      bonusesForItem(slot.itemName, effects, gearUL(slot.upgradePoints), conditionals, result, rolls);
    }
  }
  return result;
}
