/**
 * Racial skills, sourced from the SL2 wiki.
 *
 * These behave differently from class skills, and the difference is the whole
 * design of this module: not one of the 101 carries a rank or a parseable
 * numeric bonus. Their effects are conditional prose ("while at 50% HP or less,
 * they gain a bonus to SKI, CEL, LUC and GUI equal to 1 + 10% of your Scaled
 * SAN"), so there is nothing to derive without inventing numbers.
 *
 * They are therefore reference text by default. A small set the calculator
 * already models by hand is mapped to real controls in `MODELLED`, so the
 * Racials screen can offer a live toggle for exactly those and be honest that
 * the rest are informational.
 *
 * Generated by `scripts/build-race-data.mjs`.
 */
import type { RacialSkill } from '../types';
import content from '../data/content/racial-skills.json';

export type { RacialSkill };

export const RACIAL_SKILLS = content.racialSkills as RacialSkill[];

const BY_ID = new Map(RACIAL_SKILLS.map(skill => [skill.id, skill]));

const BY_SUBRACE = RACIAL_SKILLS.reduce<Record<string, RacialSkill[]>>((map, skill) => {
  for (const subrace of skill.subraces) (map[subrace] ??= []).push(skill);
  return map;
}, {});

for (const list of Object.values(BY_SUBRACE)) {
  // Actives first. They are the ones a player picks up and uses.
  list.sort((a, b) => Number(a.passive) - Number(b.passive) || a.name.localeCompare(b.name));
}

/**
 * The build field each already-modelled racial skill drives.
 *
 * `kind` tells the UI what control to draw. Anything absent from this table has
 * no calculator effect and is shown as reference only, rather than given a
 * toggle that would silently do nothing.
 */
export interface ModelledControl {
  field: string;
  kind: 'toggle' | 'redtail' | 'karakuri';
  /** What the calculator applies, as distinct from what the wiki describes. */
  hint: string;
}

export const MODELLED: Record<string, ModelledControl> = {
  'instinct-felidae': { field: 'felidaeInstinct', kind: 'toggle', hint: 'SKI / CEL / LUC / GUI at ≤50% HP, doubled at ≤25%' },
  'instinct-lupine': { field: 'lupineInstinct', kind: 'toggle', hint: 'STR / WIL / DEF / RES at ≤50% HP, doubled at ≤25%' },
  'sanguine-crest': { field: 'sanguineCrest', kind: 'toggle', hint: '+2 STR / WIL / SKI / CEL / DEF, and Dark/Light resistances' },
  // The three dice share one pair of controls: which colour, and its level.
  'red-dice': { field: 'redtailDiceColor', kind: 'redtail', hint: 'Fortune Level 1–6, scaling with SAN (+1× per 10 scaled SAN, max 5×)' },
  'green-dice': { field: 'redtailDiceColor', kind: 'redtail', hint: 'Fortune Level 1–6, scaling with SAN (+1× per 10 scaled SAN, max 5×)' },
  'yellow-dice': { field: 'redtailDiceColor', kind: 'redtail', hint: 'Fortune Level 1–6, scaling with SAN (+1× per 10 scaled SAN, max 5×)' },
  'karakuri-body': { field: 'karakuriYoukai', kind: 'karakuri', hint: 'Youkai type sets stat offsets and an elemental resistance pair' },
};

export function racialSkillById(id: string): RacialSkill | undefined {
  return BY_ID.get(id);
}

/** Every racial skill a subrace gets, actives first. */
export function racialSkillsFor(subrace: string | null | undefined): RacialSkill[] {
  if (!subrace) return [];
  return BY_SUBRACE[subrace] ?? [];
}

/** Whether this subrace has anything to show, used to gate the Racials entry. */
export function hasRacialSkills(subrace: string | null | undefined): boolean {
  return racialSkillsFor(subrace).length > 0;
}

/** The control a racial skill drives, or null when it is reference only. */
export function modelledControl(skill: RacialSkill): ModelledControl | null {
  return MODELLED[skill.id] ?? null;
}
