/**
 * Character traits.
 *
 * Traits are bought with trait points: one to start, one more every three
 * levels. Unlike skills they are not ranked (a trait is either taken or not),
 * so the modal is a set of toggles against a budget.
 *
 * Two rules from the wiki shape this module:
 *
 * - A trait's stat requirements "reference your base total. Bonuses from APT or
 *   items will not contribute", so eligibility is checked against base stats
 *   rather than the scaled ones shown in the stat block.
 * - A Human's History trait costs no trait points.
 *
 * Generated by `scripts/build-trait-data.mjs`.
 */
import type { BuildState, StatKey, StatRecord } from '../types';
import content from '../data/content/traits.json';
import { SUBRACES } from '../data/races';

/**
 * A prerequisite trait, satisfied by any one of `anyOf`.
 *
 * Alternatives exist because a few prerequisites name a pair the character picks
 * between: "Oni Heritage Trait" means either the Red or the Blue one.
 */
export interface TraitPrerequisite {
  /** The prerequisite as the wiki names it, for the ineligibility reason. */
  label: string;
  anyOf: string[];
}

/** A talent gate. The calculator does not model talent ranks, so it is shown, not enforced. */
export interface TraitTalentRequirement {
  name: string;
  rank: number;
}

export interface TraitRequirements {
  /** Minimum base stat totals, keyed by stat. */
  stats: Partial<Record<StatKey, number>>;
  races: string[];
  /** Races locked *out*, from a "Non-X Race" requirement. */
  excludedRaces: string[];
  classes: string[];
  /** Traits that must already be taken. */
  traits: TraitPrerequisite[];
  /** Talent gates, which the calculator cannot check, displayed only. */
  talents: TraitTalentRequirement[];
  /** True for "Race with Natural Skin", likewise displayed rather than checked. */
  naturalSkin: boolean;
  /**
   * Either-or clauses with a branch outside what the build models, such as
   * "10 SAN or 7+ Ranks in Spiritualism". Neither branch is enforced: checking
   * only the half that is modelled would lock a build that qualifies by the
   * other half.
   */
  alternatives: string[];
  /** The requirement as the wiki writes it, for display. */
  raw: string;
}

export interface Trait {
  id: string;
  name: string;
  category: string;
  /** Race group for a racial trait, from the wiki's subsection heading. */
  group: string | null;
  effect: string;
  statBonuses: Partial<Record<StatKey, number>>;
  requirements: TraitRequirements;
  /** True when the build already models this trait through its own control. */
  handModelled?: boolean;
  /**
   * For a History trait, the value it sets on the build's `history` field.
   *
   * History is chosen here but applied through that field, which carries HP and
   * percentage effects beyond the flat stats parsed from the wiki table.
   */
  historyKey?: string;
}

/** The History trait matching a build's `history` value, if any. */
export function historyTraitFor(history: string): Trait | undefined {
  return TRAITS.find(trait => trait.historyKey === history);
}

export const TRAITS = content.traits as Trait[];

const BY_ID = new Map(TRAITS.map(trait => [trait.id, trait]));

/** Categories in the order the wiki presents them. */
export const TRAIT_CATEGORIES = [...new Set(TRAITS.map(trait => trait.category))];

/**
 * Trait points available at a level: one to start, one more every three levels.
 *
 * Levelling gives 21 by level 60, and the legend extension bonus adds a further
 * 3 for the 24 a maxed character has. The extension grant is always counted, and
 * kept as a named constant rather than buried in the arithmetic.
 */
export const TRAIT_POINTS_FROM_LEGEND_EXTENSION = 3;

export function traitPointBudget(characterLevel: number): number {
  return 1 + Math.floor(Math.max(0, characterLevel) / 3) + TRAIT_POINTS_FROM_LEGEND_EXTENSION;
}

export function traitById(id: string): Trait | undefined {
  return BY_ID.get(id);
}

/**
 * What a trait costs this character.
 *
 * Every trait is one point, except a History trait taken by a Human race, which
 * the wiki states is free.
 */
export function traitCost(trait: Trait, race: string | null | undefined): number {
  if (trait.category === 'History' && race === 'Human') return 0;
  return 1;
}

export function traitPointsSpent(ids: string[], race: string | null | undefined): number {
  return ids.reduce((total, id) => {
    const trait = traitById(id);
    return trait ? total + traitCost(trait, race) : total;
  }, 0);
}

export interface TraitEligibility {
  eligible: boolean;
  /** Human-readable reasons the trait cannot be taken, empty when it can. */
  reasons: string[];
}

/** The stat totals a build's trait requirements are checked against. */
export type TraitCheckTarget = Pick<BuildState, 'race' | 'subrace' | 'mainClass' | 'subClass'> & {
  baseStats: Partial<StatRecord>;
  /**
   * Traits already taken, for prerequisite chains. Optional, and an absent list
   * reads as "nothing taken"; a caller that does not supply it sees every
   * chained trait as unmet, which is the safe direction to be wrong in.
   */
  taken?: string[];
};

/**
 * The base stat totals trait requirements are measured against.
 *
 * The racial line plus what the character has invested: deliberately *not*
 * `rawStats`, which folds in equipment, class and APT. The wiki is explicit that
 * "bonuses from APT or items will not contribute" to a trait requirement.
 *
 * Lives here rather than in the dialog because the optimizer rewrites
 * `addedStats` freely, and it has to test eligibility by exactly the same rule
 * the trait screen shows.
 */
export function traitCheckTarget(build: BuildState): TraitCheckTarget {
  const subrace = SUBRACES[build.subrace];
  const baseStats: Partial<StatRecord> = {};
  for (const stat of Object.keys(build.addedStats) as StatKey[]) {
    baseStats[stat] = (subrace?.[stat] ?? 0) + build.addedStats[stat] + (build.customBaseStats[stat] ?? 0);
  }
  return {
    baseStats,
    race: build.race,
    subrace: build.subrace,
    mainClass: build.mainClass,
    subClass: build.subClass,
    taken: build.traits ?? [],
  };
}

/**
 * Whether a build meets a trait's requirements.
 *
 * `baseStats` must be the base totals, not the scaled ones; the wiki is
 * explicit that APT and item bonuses do not count toward trait requirements.
 *
 * Talent gates and "Natural Skin" are deliberately not checked: the calculator
 * models neither talent ranks nor body type, so enforcing them would be
 * guesswork. They are surfaced instead through `requirements.raw`, which the
 * trait screen prints under every row.
 */
export function traitEligibility(trait: Trait, build: TraitCheckTarget): TraitEligibility {
  const reasons: string[] = [];
  const isRace = (name: string) => name === build.race || name === build.subrace;

  for (const [stat, minimum] of Object.entries(trait.requirements.stats)) {
    const have = build.baseStats[stat as StatKey] ?? 0;
    if (have < (minimum ?? 0)) reasons.push(`${String(stat).toUpperCase()} ${have}/${minimum}`);
  }

  if (trait.requirements.races.length && !trait.requirements.races.some(isRace)) {
    reasons.push(`Requires ${trait.requirements.races.join(' or ')}`);
  }

  // A "Non-X Race" requirement, which the parser used to read as needing X.
  for (const excluded of trait.requirements.excludedRaces) {
    if (isRace(excluded)) reasons.push(`Not available to ${excluded}`);
  }

  if (trait.requirements.classes.length) {
    const matches = trait.requirements.classes.some(
      required => required === build.mainClass || required === build.subClass,
    );
    if (!matches) reasons.push(`Requires ${trait.requirements.classes.join(' or ')}`);
  }

  /*
   * Prerequisite chains carry the race gate for the traits further along them
   * (the Human eyes traits name no race of their own past the first), so this
   * is a requirement, not a courtesy.
   */
  const taken = build.taken ?? [];
  for (const prerequisite of trait.requirements.traits) {
    if (!prerequisite.anyOf.some(id => taken.includes(id))) {
      reasons.push(`Requires the ${prerequisite.label} trait`);
    }
  }

  return { eligible: reasons.length === 0, reasons };
}

/**
 * Requirements the calculator shows but cannot verify.
 *
 * Talent ranks and body type are not part of the build, so a trait gated on them
 * can read as available when it is not. Naming them beats both hiding the trait
 * and implying it has been checked.
 */
export function uncheckedRequirements(trait: Trait): string[] {
  const notes = trait.requirements.talents.map(
    talent => `${talent.name} talent rank ${talent.rank}+`,
  );
  if (trait.requirements.naturalSkin) notes.push('a race with natural skin');
  notes.push(...trait.requirements.alternatives);
  return notes;
}

/**
 * Stat bonuses from the taken traits.
 *
 * Traits the build models through their own control are skipped, so a History
 * trait's stats are not counted twice.
 */
export function traitStatBonuses(ids: string[]): Partial<Record<StatKey, number>> {
  const total: Partial<Record<StatKey, number>> = {};
  for (const id of ids) {
    const trait = traitById(id);
    if (!trait || trait.handModelled) continue;
    for (const [stat, value] of Object.entries(trait.statBonuses)) {
      total[stat as StatKey] = (total[stat as StatKey] ?? 0) + (value ?? 0);
    }
  }
  return total;
}

/** Traits grouped by category, for the modal's sections. */
export function traitsByCategory(): Array<{ category: string; traits: Trait[] }> {
  return TRAIT_CATEGORIES.map(category => ({
    category,
    traits: TRAITS.filter(trait => trait.category === category),
  })).filter(group => group.traits.length > 0);
}
