/**
 * Hands, shield, legs and accessory data, equipment slots 3 to 6.
 *
 * Generated by `scripts/build-gear-data.mjs` from the scraped wiki tables and
 * loaded here the same way `armors.ts` loads armour.
 *
 * These are kept apart from `ARMORS` because they are a different shape: the
 * wiki publishes no Armor / Magic Armor / Evade / Weight for any of them, so an
 * item's whole contribution is its effect text plus whatever its material,
 * enchantment and upgrade points add.
 */

import type { GearGroup, GearItem } from '../types';
import gearData from './content/gear.json';

const GROUPS = gearData as Record<GearGroup, GearItem[]>;

/** Every gear item, grouped as the wiki groups them. */
export const GEAR_BY_GROUP: Record<GearGroup, GearItem[]> = {
  Hands: GROUPS.Hands ?? [],
  Shield: GROUPS.Shield ?? [],
  Legs: GROUPS.Legs ?? [],
  Accessory: GROUPS.Accessory ?? [],
};

/**
 * Every gear item keyed by name, which is how a build refers to one.
 *
 * Names are unique across all four groups; `build-gear-data.mjs` fails loudly if
 * that ever stops being true, since a collision would make one item unequippable.
 */
export const GEAR: Record<string, GearItem> = Object.fromEntries(
  Object.values(GEAR_BY_GROUP).flat().map(item => [item.name, item]),
);

/**
 * The items slot 3 can hold: hands pieces and shields together.
 *
 * The two are separate wiki pages but one slot, and a player choosing what to
 * put in slot 3 is choosing between all of them at once.
 */
export const SLOT3_GEAR: GearItem[] = [...GEAR_BY_GROUP.Hands, ...GEAR_BY_GROUP.Shield]
  .sort((a, b) => a.name.localeCompare(b.name));

/** Whether an item is a shield, which additionally grants the Guard skill. */
export function isShield(name: string | null | undefined): boolean {
  return Boolean(name) && GEAR_BY_GROUP.Shield.some(item => item.name === name);
}

export function gearByName(name: string | null | undefined): GearItem | undefined {
  if (!name) return undefined;
  return GEAR[name];
}
